### ISSUE TITLE
Setting dt for mujoco env

### ISSUE THREAD

**Issue by pierthodo** [ctallec/continuous-rl#1]
Hey,

I am interested in experimenting with different time discretization for mujoco and fell on your repo. To create mujoco environment like HalfCheetah you pass the parameter dt direclty. I am assuming you made changes to the gym package. Would you be able to share those changes ?

Thank you!

Pierre

**Comment by leonardblier** [comment]
Hey @pierthodo !
Yes, we modified the mujoco environments. I have just pushed my forked version of OpenAI Gym : [github.com/leonardblier/gym](https://github.com/leonardblier/gym)
For now, the way I did it is not very clean: I've created one new XML configuration file for every dt and every environment, so only some dt are available. You can add other time discretization by following the same method.

**Comment by pierthodo** [comment]
That's great thanks !
